src: fix object null prototypes being ignored
sapphiredev/type pull request #234
Opened 2021-06-15 21:55 UTC by VoltrexMaster

Objects with null prototypes are ignored, causing the static `resolve()` method to return `undefined` if the object has no constructor; it should fallback to the `Object` constructor to return a `Record` instead of `undefined` when coerced to a string, e.g.
```js
const { Type } = require('@sapphire/type');

const value = Object.create(null);

value.test = 1;

const type = new Type(value).toString();

console.log(type); // undefined
```

2021-06-15 21:56 UTC, kyranet submitted a review, later dismissed

2021-06-15 21:59 UTC, kyranet commented
Nice catch! This might have been an unintended product of a refactor.

As a side note, can you add an unit test [here](https://github.com/sapphiredev/type/blob/main/tests/objects.test.ts) to cover this specific case?

2021-06-15 22:22 UTC, kyranet requested changes
A review a day keeps the ESLint away

2021-06-15 22:22 UTC, kyranet commented on tests/objects.test.ts
> +
```suggestion

```

2021-06-15 22:28 UTC, kyranet approved these changes

2021-06-15 22:49 UTC, vladfrangu approved these changes

2021-06-16 23:25 UTC, PyroTechniac approved these changes

2021-06-18 21:53 UTC, merged